// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfybfejyqkryyfehnixb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmeWJmZWp5cWtyeXlmZWhuaXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODk2NzAsImV4cCI6MjA2NTU2NTY3MH0.EhdcHiC0pJie2ysnKVmuid9L7UGvagiqy07N-ykx4YY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);